# Generated by Django 4.2.7 on 2026-04-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_comments', to='accounts.passenger')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='safety.safetyreport')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_votes', to='accounts.passenger')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='safety.safetyreport')),
            ],
            options={
                'unique_together': {('passenger', 'report')},
            },
        ),
    ]
